### ISSUE TITLE
Configuration defaults override pg_format.conf

### ISSUE THREAD

**Issue by colinking** [bradymholt/vscode-pgFormatter#64]
**Describe the bug**

In my `pg_format.conf`, I have `no-space-function=0`. When I run pg_format via this VSCode extension, it is still inserting that space. This appears to be because the extension defaults that value to `true` and that takes precedence. Is that intentional? It's a pain to duplicate the `pg_format` config across the `pg_format.conf` (which our CI uses) and `.vscode/settings.json` (which this extension uses).

I only ran into this with `no-space-function`, but this issue should also apply to the other configuration options.

**To Reproduce**

See above.

**Prerequisites**
- [x] This is not an issue related to formatting of SQL itself.  (For formatting problems, an [issue should be created in the pgFormatter repository](https://github.com/darold/pgFormatter)).
- [x] Perl is installed on my system and when I run `perl --version` from a terminal I get information about the version of Perl installed.

**Comment by bradymholt** [comment]
> This appears to be because the extension defaults that value to true and that takes precedence. Is that intentional?

Yes, I intentionally set the default to `true` for the extension because of my preference. Hm, I hadn't considered `pg_format` being run on CI and wanting a consistent config could you just be explicit about your config in `pg_format.conf` and then use the `pgFormatter.configFile` config option to point to that file?

**Comment by colinking** [comment]
> Could you just be explicit about your config in pg_format.conf and then use the pgFormatter.configFile config option to point to that file?

That's what we're already doing, but the settings in `pg_format.conf` are getting overridden by the extension's settings.

**Comment by bradymholt** [comment]
I see.  Would you up for creating a simple repo so I can repro.?  So, the repo would have a `pg_format.conf`, a `.sql` file and maybe an example command that runs `pg_format`?

**Comment by colinking** [comment]
Here you go: https://github.com/colinking/pg_format_issue

This has the following config:

```
spaces=4
no-space-function=0
```

But both settings are overridden:

<img width="1392" alt="CleanShot 2023-04-18 at 12 26 44" src="https://user-images.githubusercontent.com/2907397/232842720-1d53d47b-7403-4e6a-af75-fc82f27de42b.png">

**Comment by bradymholt** [comment]
https://github.com/bradymholt/vscode-pgFormatter/pull/65 should fix this by disabling all other settings when a `configFile` setting is specified.  This change has been released as [v1.25.0](https://github.com/bradymholt/vscode-pgFormatter/releases/tag/v1.25.0).

@colinking - In your demo project I don't think the config file was being resolved because it needed an absolute path.  I've updated the README.md to recommend using a variable like this: `${workspaceFolder}/pg_format.conf` so it will be resolved with an absolute path.  Even with that, the extension settings were still overriding config in `pg_format.conf` and that PR should fix it.  Please note the change in that PR disables all extension settings if a `configFile` setting is specified.

**Comment by colinking** [comment]
Fantastic, thanks @bradymholt! However, we configure `extra-function` as a relative path from the workspace folder and that doesn't work with `v1.25.0` (we get a `FATAL: file for extra function list does not exists: db/pg_format/extra_functions.txt` error when trying to format a file). We have the following in our `pg_format.conf`:

```
# Add a list of function to be formatted as PG internal functions
extra-function=db/pg_format/extra_functions.txt
```

This works fine when we run `pg_format` directly from the workspace folder. Could `pgFormatter.extraFunction` also be passed in when `pgFormatter.configFile` is set? If so, we can set `"pgFormatter.extraFunction": "${workspaceFolder}/db/pg_format/extra_functions.txt",` and that should work.

**Comment by bradymholt** [comment]
I just merged https://github.com/bradymholt/vscode-pgFormatter/pull/66 and the new release will go out soon.  Now, extension config will still be passed if you specify `configFile` setting.  If you want to avoid a default setting for the extension overriding a setting in your `pg_format.conf` file, you can specify the value as `null`.  See the latest README explanation for `configFile` for details.

**Comment by ggPeti** [comment]
@bradymholt the new behavior prevents this extension from being a recommendation in teams, because each user's VSCode configuration may be different. It's very awkward to suggest to each team member to manually set each setting to null, just in order to apply the pg_format config committed to the repo uniformly. I think the behavior from #65 is preferable.

**Comment by bradymholt** [comment]
@ggPeti Do you have a suggestion for a change to fix your issue while also preserving the fix in this PR?
